#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Support\Collection;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

try {
    require_once __DIR__.'/vendor/autoload.php';

    $dispatcher = new Dispatcher();
    $container = new Container();
    $app = new Application($container, $dispatcher, '0.1');
    $app->setName('Calculator');
    $commands = require_once __DIR__.'/commands.php';
    $commands = (new Collection($commands))
        ->map(function ($command) use ($app) {
            return $app->getLaravel()->make($command);
        })->all();
    $app->addCommands($commands);
    $app->run(new ArgvInput(), new ConsoleOutput());
} catch (\Throwable $e) {
    echo 'Caught exception: ', $e->getMessage()."\n", $e->getTraceAsString(),"\n";
}
